snacks = [
    "Doritos",
    "Lays Sour Cream 'n Onion",
    "Lays",
    "Snickers",
    "Reese's",
    "Heath Bar",
    "Cheetos",
    "Ruffles",
    "Clif Bar",
    "Pop-Tart",
    "Sun Chips Original",
    "Sun Chips French Onion",
    "Planters Trail Mix",
    "Granola Bars",
    "Cheez-its",
    "Chex Mix",
    "Pretzels",
    "Cup o Noodles",
    "Apple",
    "Orange",
    "Banana",
    "Blueberries",
    "Gatorade Frost Cherry",
    "Vitamin Water",
    "Powerade Red",
    "Powerade Blue",
    "Powerade Orange",
    "Powerade Burst Cherry",
    "Powerade Refreshing Punch",
    "Powerade Fierce Orange",
    "Coke",
    "Pepsi",
    "Dr. Pepper",
    "Water",
    "Sprite",
    "Mountain Dew",
    "Mr. Pibb",
    "Diet Coke",
    "Diet Pepsi",
    "Gold Peak Tea",
    "Lipton Tea",
    "Brisk Tea",
    "Honest Tea",
    "La Croix",
    "Polar",
    "Perrier",
    "Minute Maid",
    "Simply Lemonade",
    "Newman's",
    "Tropicana",
    "Three Muskateers",
    "Smarties",
    "Sour Patch Kids",
    "Oreos",
    "Nutter Butter",
    "Nature Bars",
    "Chips Ahoy",
]
